version: '3.8'

services:
  jenkins:
    image: jenkins/jenkins:lts-jdk17
    container_name: jenkins
    ports:
      - "9090:8080"
      - "50000:50000"
    volumes:
      - jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
    networks:
      - mynet

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    networks:
      - mynet
    depends_on:
      - jenkins

  frontend:
    build:
      context: ./frontend/app
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - mynet
    depends_on:
      - backend

  amazon-scraper:
    build:
      context: ./webScrapping/amazon
      dockerfile: Dockerfile
    ports:
      - "8085:8085"
    networks:
      - mynet

volumes:
  jenkins_data:

networks:
  mynet: