services:
  jenkins:
    image: jenkins/jenkins:lts-jdk17
    container_name: jenkins
    ports:
      - "9090:8080"
      - "50000:50000"
    volumes:
      - jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
    networks:
      - mynet

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      - mynet
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"] # Add health endpoint to your backend
      interval: 30s
      timeout: 10s
      retries: 3
    depends_on:
      jenkins:
        condition: service_started

  webscrapping:
    build:
      context: ./webscrapping/amazon
      dockerfile: Dockerfile
    ports:
      - "8085:8085"
    networks:
      - mynet
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8085"]
      interval: 30s
      timeout: 10s
      retries: 3
    depends_on:
      backend:
        condition: service_healthy

volumes:
  jenkins_data:

networks:
  mynet: