version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8082:8082"  # Host:Container port mapping (now 8082)
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend/app
      dockerfile: Dockerfile
    ports:
      - "80:80"  # Frontend remains on port 80
    depends_on:
      - backend
    restart: unless-stopped